# Generated by Django 6.0.1 on 2026-07-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PASSWORD_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='Username')),
            ],
        ),
    ]
